### ISSUE TITLE
RangeError: minimumFractionDigits value is out of range.

### ISSUE THREAD

**Issue by pcdv** [parttimenerd/intellij-profiler-plugin#24]
Got this error shortly after opening a jfr file. Happens when scrolling in the thread list, or clicking in it.

Afraid I can't share the .jfr causing the issue because it contains proprietary data :(

```
RangeError: minimumFractionDigits value is out of range.

    at SampleTooltipCPUContents (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:20579:1)
    at SampleTooltipContents (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:20641:1)
    at div
    at Tooltip (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:36184:5)
    at div
    at ThreadActivityGraphImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:23637:5)
    at WithSizeWrapper (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:22549:7)
    at div
    at TimelineTrackThreadImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:33622:5)
    at WithSizeWrapper (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:22549:7)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at div
    at div
    at li
    at LocalTrackComponent (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:27817:5)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at ol
    at Reorderable (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:20351:5)
    at li
    at GlobalTrackComponent (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:27480:5)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at ol
    at Reorderable (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:20351:5)
    at div
    at div
    at div
    at OverflowEdgeIndicator (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:28791:5)
    at div
    at TimelineRulerAndSelection (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:29021:5)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at FullTimelineImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:27354:5)
    at WithSizeWrapper (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:22549:7)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at TimelineImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:34379:5)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at div
    at s (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:108164:1311)
    at div
    at t (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:108164:2960)
    at div
    at div
    at KeyboardShortcut (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:9500:5)
    at ProfileViewerImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:12185:1)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at AppViewRouterImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:7830:1)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at UrlManagerImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:13078:5)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at div
    at DragAndDropImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:8753:5)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at LocalizationProvider (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:123623:145)
    at AppLocalizationProviderImpl (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:7721:1)
    at ConnectFunction (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106639:114)
    at Provider (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:106352:3)
    at ErrorBoundary (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:8921:5)
    at Root (http://localhost:4243/main.5f6d6684f429b779a851.bundle.js:12316:1)
```

**Comment by pcdv** [comment]
Not sure if related, but I got the issue when opening a jfr made with JDK21 (previous tests were done with JDK17)

**Comment by parttimenerd** [comment]
The JFR file being confidential doesn't make it that easy to debug, but I can certainly make the failing method more resilient.

**Comment by o-oconnell** [comment]
+1

**Comment by parttimenerd** [comment]
I made the related number formatting more robust by replacing invalid minimumFractionDigits with zero. I hope this fixes it, a new plugin version is submitted.

**Comment by pcdv** [comment]
Thanks, I opened a JDK21 JFR without a problem. Unfortunately, I can't remember where I kept the particular JFR that caused the issue so I can't 100% certify that the bug is fixed :)

Closing the issue. I will reopen and try adding more info in case it occurs again.
