### ISSUE TITLE
Profiler crash sometime

### ISSUE THREAD

**Issue by SettingDust** [parttimenerd/intellij-profiler-plugin#31]
**Describe the bug**
```
RangeError: minimumFractionDigits value is out of range.

    at SampleTooltipCPUContents (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:20579:1)
    at SampleTooltipContents (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:20641:1)
    at div
    at Tooltip (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:36184:5)
    at div
    at ThreadActivityGraphImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:23637:5)
    at WithSizeWrapper (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:22549:7)
    at div
    at TimelineTrackThreadImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:33622:5)
    at WithSizeWrapper (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:22549:7)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at div
    at div
    at li
    at LocalTrackComponent (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:27817:5)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at ol
    at Reorderable (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:20351:5)
    at li
    at GlobalTrackComponent (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:27480:5)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at ol
    at Reorderable (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:20351:5)
    at div
    at div
    at div
    at OverflowEdgeIndicator (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:28791:5)
    at div
    at TimelineRulerAndSelection (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:29021:5)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at FullTimelineImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:27354:5)
    at WithSizeWrapper (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:22549:7)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at TimelineImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:34379:5)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at div
    at s (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:108168:1311)
    at div
    at t (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:108168:2960)
    at div
    at div
    at KeyboardShortcut (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:9500:5)
    at ProfileViewerImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:12185:1)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at AppViewRouterImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:7830:1)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at UrlManagerImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:13078:5)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at div
    at DragAndDropImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:8753:5)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at LocalizationProvider (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:123627:145)
    at AppLocalizationProviderImpl (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:7721:1)
    at ConnectFunction (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106643:114)
    at Provider (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:106356:3)
    at ErrorBoundary (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:8921:5)
    at Root (http://localhost:4243/main.eecb992314f4573d837f.bundle.js:12316:1)
```

**To Reproduce**
Move the cursor to the timeline on the top part

[client-2024-08-14-184805.zip](https://github.com/user-attachments/files/16612281/client-2024-08-14-184805.zip)

**Screenshots**
![图片](https://github.com/user-attachments/assets/e2943929-643c-45b1-93c7-c4f04bcc1e10)

**Comment by parttimenerd** [comment]
Thanks, it's on my agenda, I'll hope to get working on it next week.

**Comment by nicolasassi** [comment]
It seems that the problem is still happening.

**Comment by jsoref** [comment]
Triggered today w/ 0.0.14; IntelliJ IDEA 2025.1.3 (Community Edition); Sequioa 15.5 (m1)
- https://github.com/firefox-devtools/profiler/pull/5086
