### ISSUE TITLE
NPE after first run

### ISSUE THREAD

**Issue by JohannesLichtenberger** [parttimenerd/intellij-profiler-plugin#5]
```java
java.lang.NullPointerException
	at me.bechberger.jfrplugin.config.ProfilerConfig.getJFRVirtualFile(Config.kt:77)
	at me.bechberger.jfrplugin.config.ConfigKt.getJfrVirtualFile(Config.kt:117)
	at me.bechberger.jfrplugin.runner.ap.APProgramRunner$workWithDescriptor$1.processTerminated$lambda$0(APProgramRunner.kt:87)java.lang.NullPointerException
	at me.bechberger.jfrplugin.config.ProfilerConfig.getJFRVirtualFile(Config.kt:77)
	at me.bechberger.jfrplugin.config.ConfigKt.getJfrVirtualFile(Config.kt:117)
	at 
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
```

I'm got the following NPE after the first run of a method I want to profile. Seems there's a config file missing? The next time I tried no exception was raised, but also no flamegraph... was presented after the run.

Thanks for your impressive work :+1:

**Comment by parttimenerd** [comment]
Thanks for catching it.

**Comment by parttimenerd** [comment]
The NPE comes due to a failure of creating the `profile.jfr` file. What JDK are you using? Did you use JFR or async-profiler mode?

**Comment by JohannesLichtenberger** [comment]
IIRC I've used GraalVM 19 with the async-profiler mode, but it doesn't matter. I've tried both.

**Comment by JohannesLichtenberger** [comment]
Currently I'm on another laptop

**Comment by parttimenerd** [comment]
Interesting. I never tried GraalVM with my IDE.

**Comment by JohannesLichtenberger** [comment]
I think it's a new JDK option since a couple of months, maybe :-) I wanted to check if the JIT compiler has any positive effects regarding my spare time DB project, but doesn't make much difference I think.

**Comment by JohannesLichtenberger** [comment]
You can simply download the JDK via IntelliJ and check if that's the issue :-)

**Comment by parttimenerd** [comment]
I see some issues with GraalVM and try to fix them tomorrow.
