### ISSUE TITLE
Plugin is unusable on Windows 11

### ISSUE THREAD

**Issue by lehvolk** [parttimenerd/intellij-profiler-plugin#7]
```
java.lang.IllegalStateException: Async-profiler does not work on windows 11
	at one.profiler.AsyncProfilerLoader.getLibrarySuffix(AsyncProfilerLoader.java:153)
	at one.profiler.AsyncProfilerLoader.getAsyncProfilerFileName(AsyncProfilerLoader.java:214)
	at one.profiler.AsyncProfilerLoader.isSupported(AsyncProfilerLoader.java:256)
	at me.bechberger.jfrplugin.runner.ap.APPluginRunConfigurationExtension.isEnabledFor(APPluginRunConfigurationExtension.kt:24)
	at me.bechberger.jfrplugin.runner.ap.APPluginRunConfigurationExtension.isApplicableFor(APPluginRunConfigurationExtension.kt:34)
	at com.intellij.execution.configuration.RunConfigurationExtensionsManager.writeExternal(RunConfigurationExtensionsManager.kt:241)
	at com.intellij.execution.ExternalSystemRunConfigurationJavaExtension.writeExternal(ExternalSystemRunConfigurationJavaExtension.kt:33)
	at com.intellij.execution.ExternalSystemRunConfigurationJavaExtension.writeExternal(ExternalSystemRunConfigurationJavaExtension.kt:17)
	at com.intellij.execution.configuration.RunConfigurationExtensionsManager.writeExternal(RunConfigurationExtensionsManager.kt:86)
	at com.intellij.openapi.externalSystem.service.execution.configuration.ExternalSystemRunConfigurationExtensionManager$Companion.writeExternal(ExternalSystemRunConfigurationExtensionManager.kt:52)
	at com.intellij.openapi.externalSystem.service.execution.configuration.ExternalSystemRunConfigurationExtensionManager.writeExternal(ExternalSystemRunConfigurationExtensionManager.kt)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration.writeExternal(ExternalSystemRunConfiguration.java:189)
	at org.jetbrains.plugins.gradle.service.execution.GradleRunConfiguration.writeExternal(GradleRunConfiguration.java:116)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration.clone(ExternalSystemRunConfiguration.java:118)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunConfiguration.clone(ExternalSystemRunConfiguration.java:66)
	at com.intellij.execution.configurations.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:41)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:278)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfigurationStatic(RunConfigurationProducer.java:257)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfiguration(RunConfigurationProducer.java:247)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:96)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:119)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:100)
	at com.intellij.execution.actions.ConfigurationContext.createConfigurationsFromContext(ConfigurationContext.java:423)
	at com.intellij.execution.ExecutorRegistryImpl$ExecutorAction.getRunConfigsForCurrentFile(ExecutorRegistryImpl.java:503)
	at com.intellij.execution.ui.RedesignedRunToolbarWrapper.isSomeRunningNow(RedesignedRunWidget.kt:101)
	at com.intellij.execution.ui.RedesignedRunToolbarWrapper.update(RedesignedRunWidget.kt:87)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:157)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:180)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:720)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$5(ActionUpdater.java:186)
	at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:556)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:606)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$23(ActionUpdater.java:529)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1406)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:529)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:309)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$14(ActionUpdater.java:377)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$15(ActionUpdater.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$16(ActionUpdater.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroupAsync$17(ActionUpdater.java:395)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It will be nice not to fail in this case and make plugin usable but without async-profiler run configuration.

**Comment by parttimenerd** [comment]
Thanks for your bug report, this is a problem with the underlying ap-loader library. `AsyncProfilerLoader.isSupported` should definitely work without throwing any exceptions.

**Comment by parttimenerd** [comment]
I found and fixed the problem in ap-loader and will be creating a new plugin build this afternoon.

**Comment by lehvolk** [comment]
Wow. Very fast. Thanks a lot. Appreciate a lot your efforts. Will try it when it will be ready.

**Comment by parttimenerd** [comment]
The release 0.0.5 should have fixed it.

**Comment by lehvolk** [comment]
Confirmed. Plugin is working.
